// Native Chrome DevTools verification; uses the project's running UI and API.
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root = path.resolve(import.meta.dirname, '..');
const targets = await (await fetch('http://127.0.0.1:9222/json')).json();
const socket = new WebSocket(targets.find(t => t.type === 'page').webSocketDebuggerUrl);
await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
let sequence = 0;
const pending = new Map(), report = { checks: [], observations: {}, errors: [] };
socket.onmessage = event => {
  const m = JSON.parse(event.data);
  if (pending.has(m.id)) { const p = pending.get(m.id); pending.delete(m.id); m.error ? p.reject(m.error) : p.resolve(m.result); }
  if (m.method === 'Runtime.exceptionThrown') report.errors.push(m.params.exceptionDetails.exception?.description || m.params.exceptionDetails.text);
};
const send = (method, params = {}) => new Promise((resolve, reject) => { const id = ++sequence; pending.set(id, { resolve, reject }); socket.send(JSON.stringify({ id, method, params })); });
const evaluate = async expression => { const r = await send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (r.exceptionDetails) throw Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text); return r.result.value; };
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function waitFor(expression, timeout = 30000) { const start = Date.now(); while (Date.now() - start < timeout) { if (await evaluate(expression).catch(() => false)) return; await delay(40); } throw Error('Timed out: ' + expression); }
async function navigate(route) { await send('Page.navigate', { url: 'http://127.0.0.1:3000' + route }); await waitFor(`location.pathname === ${JSON.stringify(route.split('?')[0])} && !!document.querySelector('main h1')`); await delay(1600); }
const click = text => evaluate(`[...document.querySelectorAll('button')].find(b=>b.textContent.includes(${JSON.stringify(text)})).click()`);
const check = name => { report.checks.push(name); console.log('PASS', name); };
try {
  await send('Page.enable'); await send('Runtime.enable');
  await send('Emulation.setFocusEmulationEnabled', { enabled: true });
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] });
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1040, deviceScaleFactor: 1, mobile: false });
  await navigate('/'); await evaluate('sessionStorage.removeItem("arthopilot-motion-paused")'); await navigate('/');
  assert.ok(await evaluate('getComputedStyle(document.querySelector(".preview-metrics strong")).fontSize === getComputedStyle(document.querySelector(".preview-metrics .number-display")).fontSize'));
  assert.equal(await evaluate('document.querySelector(".agent-feature").dataset.reveal'), 'pending');
  await evaluate('document.querySelector(".agent-feature").scrollIntoView({block:"center"})');
  await waitFor('document.querySelector(".agent-feature").dataset.reveal === "shown"');
  await delay(800);
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".agent-feature")).opacity'), '1');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".hero-product")).animationPlayState'), 'paused');
  check('Progressive section reveal and offscreen ambient suspension');
  await evaluate('window.scrollTo(0,0)'); await delay(400);
  assert.ok(await evaluate('document.querySelector(".hero-product-scene").style.getPropertyValue("--hero-y")'));
  await evaluate('document.querySelector(".motion-toggle").click()');
  const notification = await evaluate('document.querySelector(".floating-transaction strong").textContent');
  await delay(10400);
  assert.equal(await evaluate('document.querySelector(".floating-transaction strong").textContent'), notification);
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".hero-product")).animationName'), 'none');
  check('Pause control stops ambient CSS motion and rotating content');
  await navigate('/dashboard/');
  assert.equal(await evaluate('document.querySelector(".motion-toggle").getAttribute("aria-pressed")'), 'true');
  await evaluate('document.querySelector(".motion-toggle").click()'); await delay(900);
  await click('Demo preview'); await delay(100);
  const intermediate = await evaluate('document.querySelector(".metric .number-display").textContent');
  await delay(950);
  const finalValue = await evaluate('document.querySelector(".metric .number-display").textContent');
  assert.notEqual(intermediate, finalValue); assert.equal(finalValue, '৳12,500');
  report.observations.countUp = { intermediate, finalValue };
  assert.equal(await evaluate('document.querySelector(".metric .number-reserve").textContent'), finalValue);
  check('Metrics interpolate, settle exactly, and expose stable accessible values');
  assert.ok(await evaluate('getComputedStyle(document.querySelector(".chart-trace")).animationName.includes("chart-draw")'));
  await evaluate('document.querySelector(".chart rect[role=button]").focus()');
  await waitFor('document.querySelector(".chart").textContent.includes("৳")');
  check('Chart draw animation and keyboard data inspection');
  await navigate('/agents/');
  assert.equal(await evaluate('document.querySelectorAll(".network-signal").length'), 4);
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".network-signal")).animationDuration'), '10s');
  check('Four slow agent connection signals');
  const stub = await send('Page.addScriptToEvaluateOnNewDocument', { source: 'window.SpeechRecognition = class { start(){window.__recognition=this} stop(){this.onend?.()} };' });
  await navigate('/voice/');
  await evaluate('document.querySelector(".main-mic").click()');
  await waitFor('document.querySelector(".voice-experience").dataset.stage === "listening"');
  assert.ok(await evaluate('document.querySelector(".waveform").classList.contains("active")'));
  await evaluate('window.__recognition.onresult({results:[[{transcript:"আজকে ৫০০ টাকার বিক্রি হয়েছে"}]]});window.__recognition.stop()');
  await waitFor('document.querySelector(".voice-experience").dataset.stage === "ready"');
  await click('Understand my transaction');
  await waitFor('document.querySelector(".voice-experience").dataset.stage === "understanding"');
  await waitFor('document.querySelector(".voice-experience").dataset.stage === "finding"');
  await waitFor('document.querySelector(".voice-experience").dataset.stage === "preview"');
  assert.ok(await evaluate('document.querySelector(".transaction-preview").textContent.includes("500")'));
  await send('Page.removeScriptToEvaluateOnNewDocument', { identifier: stub.identifier });
  check('Simulated microphone lifecycle; real API understanding, finding, and preview states');
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] });
  await navigate('/');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".hero-product")).animationName'), 'none');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".agent-feature")).opacity'), '1');
  assert.equal(await evaluate('document.querySelector(".preview-metrics .number-display").textContent'), '৳12,500');
  check('Reduced motion shows all content and exact figures without movement');
  await send('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'no-preference' }] });
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true });
  await send('Emulation.setTouchEmulationEnabled', { enabled: true });
  await navigate('/');
  assert.equal(await evaluate('getComputedStyle(document.querySelector(".hero-product")).animationName'), 'none');
  assert.ok(await evaluate('document.documentElement.scrollWidth <= innerWidth'));
  await navigate('/insights/?demo=1');
  await evaluate('document.querySelector(".chart").scrollIntoView({block:"center"})'); await delay(300);
  const point = await evaluate('(()=>{const r=document.querySelector(".chart rect[role=button]").getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()');
  await send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [point] });
  await send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await waitFor('document.querySelector(".chart").textContent.includes("৳")');
  check('Mobile hero remains steady and chart data responds to touch');
  assert.equal(report.errors.length, 0, report.errors.join('\n'));
} finally {
  await send('Emulation.setTouchEmulationEnabled', { enabled: false }).catch(() => {});
  await fs.writeFile(path.join(root, 'screenshots', 'motion-verification.json'), JSON.stringify(report, null, 2));
  socket.close();
}
