import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#d3e3ff",
        "tertiary-fixed": "#84fe58",
        error: "#ba1a1a",
        "surface-border": "#E2E8F0",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f4f",
        "growth-green": "#38B000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#36ab00",
        "on-secondary": "#ffffff",
        "danger-rose": "#E11D48",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#0b3500",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#bcc9c8",
        "inverse-primary": "#5bd9d8",
        "on-tertiary-fixed": "#052100",
        "on-surface-variant": "#3d4949",
        "on-secondary-fixed-variant": "#28486f",
        background: "#f8f9ff",
        "deep-navy": "#12355B",
        "on-surface": "#0b1c30",
        "primary-fixed": "#7af5f5",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#001c39",
        "on-error": "#ffffff",
        "on-primary-container": "#003434",
        "primary-fixed-dim": "#5bd9d8",
        "surface-tint": "#006a6a",
        "surface-bright": "#f8f9ff",
        primary: "#006a6a",
        "vibrant-teal": "#00A6A6",
        "on-primary-fixed": "#002020",
        "inverse-surface": "#213145",
        "secondary-container": "#b2d1ff",
        secondary: "#416088",
        tertiary: "#206d00",
        "warning-amber": "#F59E0B",
        "surface-container-low": "#eff4ff",
        outline: "#6c7a79",
        "surface-container-high": "#dce9ff",
        "primary-container": "#00a6a6",
        "bg-canvas": "#F8FAFC",
        surface: "#FFFFFF",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-fixed-variant": "#165200",
        "tertiary-fixed-dim": "#69e03e",
        "on-secondary-container": "#3b5981",
        "secondary-fixed-dim": "#aac8f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        "gutter-md": "1.5rem",
        "gutter-lg": "2rem",
        margin: "1rem",
        "margin-md": "2rem",
        "margin-lg": "3rem",
      },
      fontFamily: {
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "42px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      }
    },
  },
  plugins: [],
};

export default config;
