"use client";
import Link from "next/link";
import { useState, useRef } from "react";
import { ArrowUpRight, ArrowRight, Check, Play, Network, Sparkles, Radio } from "lucide-react";
import { agents, BrandMark, PageHeading, Status } from "@/components/product/Primitives";
import { api, apiError, AgentResponse } from "@/lib/api";
import { AgentConnections } from "@/components/product/Motion";
const scenarios = [
 {name:"Payment verification", message:"SMS: ১৫০০ টাকার বিকাশ পেমেন্ট পেয়েছেন।", description:"Screen a payment message with Pahara."},
 {name:"Suspicious message", message:"জরুরি: OTP দিন https://payment-check.xyz", description:"See how an urgent credential request is assessed."},
 {name:"Day-end review", message:"ব্যবসার লাভ কেমন?", description:"Summarize the records already in your ledger."}
];
export default function AgentsPage() {
 const [selected,setSelected]=useState(0); const [scenario,setScenario]=useState(0); const [running,setRunning]=useState(false);
 const [message,setMessage]=useState(agents[0].prompt); const [response,setResponse]=useState<AgentResponse|null>(null); const [error,setError]=useState(""); const guard=useRef(false);
 const agent=agents[selected];
 const run=async(useScenario=false)=>{if(guard.current)return;guard.current=true;setRunning(true);setError("");setResponse(null);try{setResponse(await api.chat(useScenario?scenarios[scenario].message:message,{save:false,...(useScenario?{}:{agent:agent.id})}));}catch(e){setError(apiError(e));}finally{guard.current=false;setRunning(false);}};
 return <div className="product-page agents-page"><PageHeading eyebrow="THE INTELLIGENCE BEHIND YOUR EVERYDAY" title="One core. A team in your corner." description="Four focused agents. One shared purpose: helping your business move forward." action={<Status><Network size={13}/>4 specialized agents</Status>}/>
 <div className="ecosystem-layout"><section className="ecosystem-panel"><div className="ecosystem-top"><span className="micro-label">ARTHOPILOT AGENT NETWORK</span><span><i className="live-dot"/>Interactive explorer</span></div><div className={`ecosystem-map ${running?"running":""}`}><div className="ecosystem-orbit orbit-a"/><div className="ecosystem-orbit orbit-b"/><AgentConnections/><div className="ai-core"><div className="ai-core-glow"/><BrandMark/><strong>ArthoPilot</strong><span>AI CORE</span><small>{running?"Working on your request":"Understand. Connect. Guide."}</small></div>{agents.map((a,i)=><button key={a.id} onClick={()=>{if(!running){setSelected(i);setMessage(a.prompt);setResponse(null);}}} className={`agent-node node-${i} ${a.color} ${selected===i?"selected":""}`} aria-pressed={selected===i} disabled={running}><span className="node-icon"><a.icon size={25}/><i/></span><strong>{a.name}</strong><span>{a.role}</span><small>{a.bn}</small></button>)}</div><div className="ecosystem-bottom"><span><span className="connection-dot"/>Connected by a shared purpose</span><span>Select an agent to explore <ArrowUpRight size={13}/></span></div></section>
 <aside className={`panel agent-detail ${agent.color}`}><div className="agent-detail-top"><span className="node-icon"><agent.icon size={25}/></span><span className="micro-label">MEET YOUR AGENT</span></div><h2>{agent.name}<span>{agent.bn}</span></h2><span className="agent-role">{agent.role}</span><p>{agent.description}</p><div className="agent-capabilities">{(selected===0?["Bangla transaction understanding","Sales & expense categorization","Review before saving"]:selected===1?["Suspicious message screening","Clear risk explanations","Practical next steps"]:selected===2?["Search your business documents","Source-backed explanations","Clear when evidence is missing"]:["Recorded sales & expense trends","Weekly comparisons","Simple Bangla suggestions"]).map(t=><span key={t}><Check size={14}/>{t}</span>)}</div><Link className="inline-link" href={agent.href}>Explore {agent.name} <ArrowUpRight size={16}/></Link><div className="agent-detail-note"><Sparkles size={15}/>Tools that help you decide. You stay in control.</div></aside></div>
 <section className="panel agent-playground"><div className="panel-heading"><div><span className="micro-label">SEE THE THINKING IN ACTION</span><h2>A real request. A clear next step.</h2></div><Status tone="neutral">Preview only · no ledger writes</Status></div><div className="agent-playground-grid"><div><label className="field-label" htmlFor="agent-message">Ask {agent.name}</label><textarea id="agent-message" rows={3} value={message} onChange={e=>setMessage(e.target.value)} maxLength={8000} disabled={running}/><button className="button navy" onClick={()=>run()} disabled={running||!message.trim()}>{running?"Agent is working…":"Run with "+agent.name}<ArrowRight size={16}/></button></div><div className="scenario-box"><label className="field-label" htmlFor="scenario">Or explore a workflow</label><select id="scenario" value={scenario} onChange={e=>setScenario(Number(e.target.value))} disabled={running}>{scenarios.map((s,i)=><option value={i} key={s.name}>{s.name}</option>)}</select><p>{scenarios[scenario].description}</p><button className="button soft" onClick={()=>run(true)} disabled={running}><Play size={14}/>Run scenario</button></div></div>{error&&<p role="alert" className="form-error">{error}</p>}{response&&<div className="agent-result" role="status"><div className="execution-trace">{response.trace?.map((step,i)=><span key={step}><Check size={12}/>{step.replaceAll("_"," ")}{i<2&&<ArrowRight size={12}/>}</span>)}</div><strong>{response.agent?.toUpperCase()||"ARTHOPILOT"} · {response.status.replaceAll("_"," ")}</strong><p>{response.message}</p>{response.citations.map(c=><blockquote key={c.source+c.chunk}><small>{c.source} · section {c.chunk}</small><p>{c.excerpt}</p></blockquote>)}</div>}</section></div>;
}
