"use client";
import { ArrowDownToLine, ArrowUpRight, TrendingUp, RefreshCw, ArrowRight, Sparkles } from "lucide-react";
import { useState } from "react";
import Link from "next/link";
import { useApp } from "@/context/AppContext";
import { useInsights } from "@/lib/useInsights";
import { demoSales, demoExpenses, demoLabels } from "@/lib/demoData";
import { AIInsight, Chart, DataSwitch, Metric, PageHeading, Status, money, useDemo } from "@/components/product/Primitives";

export default function InsightsPage() {
  const { transactions } = useApp();
  const [demo, setDemo] = useDemo();
  const [revision, setRevision] = useState(0);
  const { result, error, loading } = useInsights(transactions.length + revision);
  const [metric, setMetric] = useState("sales");
  const data = result?.insights;
  const daily = data?.daily || [];
  const sales = demo ? demoSales : daily.length ? daily.map(d => d.sales) : Array(7).fill(0);
  const expenses = demo ? demoExpenses : daily.length ? daily.map(d => d.expenses) : Array(7).fill(0);
  const labels = demo ? demoLabels : daily.length ? daily.map(d => d.date.slice(5)) : demoLabels;
  const totalSales = sales.reduce((a, b) => a + b, 0);
  const totalExpenses = expenses.reduce((a, b) => a + b, 0);
  const growth = demo ? 18 : data?.sales_change_percent;
  const exportData = () => {
    const csv = "date,sales,expenses,source\n" + labels.map((label, i) => `${label},${sales[i]},${expenses[i]},${demo ? "demo" : "recorded"}`).join("\n");
    const link = document.createElement("a"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.href = url; link.download = `arthopilot-${demo ? "demo" : "recorded"}-insights.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className="product-page insights-page"><PageHeading eyebrow="UNNOTI · YOUR GROWTH ADVISOR" title="See the progress. Find the possibility." description="Less noise in the numbers. More confidence in your next move." action={<button className="button white" onClick={exportData}><ArrowDownToLine size={16}/>Export report</button>}/><div className="insights-toolbar"><div><Status>Weekly business view</Status><span className="muted">{demo ? "Illustrative week · sample data" : data ? `${data.period_start} — ${data.period_end}` : "Latest 7 days · Asia/Dhaka"}</span></div><DataSwitch demo={demo} onChange={setDemo}/></div>
  <div className="insight-metrics"><Metric label="Total sales" value={money(totalSales)} detail={growth != null ? `${growth >= 0 ? "↗" : "↘"} ${growth}% vs previous week` : "No comparison baseline"}/><Metric label="Total expenses" value={money(totalExpenses)} detail="Know where your money goes" positive={false}/><Metric label="Net cash flow" value={money(totalSales - totalExpenses)} detail="Recorded sales less expenses"/><div className="growth-highlight"><TrendingUp size={23}/><span>WEEKLY SALES GROWTH</span><strong>{growth != null ? `${growth > 0 ? "+" : ""}${growth}%` : "—"}</strong><p>{growth != null ? "A clearer view of your momentum." : "Add records over time to compare."}</p></div></div>
  <section className="panel main-analytics"><div className="panel-heading"><div><span className="micro-label">SMALL STEPS. VISIBLE PROGRESS.</span><h2>Your business has a story to tell.</h2></div><div className="segmented">{["sales", "expenses", "growth"].map(m => <button key={m} onClick={() => setMetric(m)} className={metric === m ? "selected" : ""} aria-pressed={metric === m}>{m[0].toUpperCase() + m.slice(1)}</button>)}</div></div><div className="analytics-hero-number"><strong>{money(metric === "expenses" ? totalExpenses : metric === "growth" ? totalSales - totalExpenses : totalSales)}</strong><span>{metric === "sales" ? "Sales this period" : metric === "expenses" ? "Expenses this period" : "Daily net cash flow"}</span><div className="chart-legend"><span><i/>{metric === "expenses" ? "Expenses" : metric === "growth" ? "Net cash flow" : "Sales"}</span>{metric === "sales" && <span><i className="gray"/>Expenses</span>}</div></div><Chart sales={metric === "expenses" ? expenses : metric === "growth" ? sales.map((s, i) => s - expenses[i]) : sales} expenses={metric === "sales" ? expenses : undefined} labels={labels} title={metric}/><AIInsight title={demo ? "Your sales increased 18% compared to last week." : growth != null ? `Recorded sales changed ${growth}% from the previous week.` : "Your next chapter starts with good records."}><p>{demo ? "Your strongest days are toward the end of the week. Keep your popular items stocked and give yourself a little room to grow." : error || result?.message || "Looking at your recorded activity…"}</p></AIInsight></section>
  <div className="insights-bottom"><section className="panel expense-breakdown"><span className="micro-label">A CLOSER LOOK AT SPENDING</span><h2>Make every taka count.</h2>{(demo ? [{ label: "Inventory & supplies", value: 62 }, { label: "Shop & utilities", value: 24 }, { label: "Delivery & other", value: 14 }] : (() => { const categories: Record<string, number> = {}; transactions.filter(t => t.type === "outflow" && t.createdAt && data && t.createdAt.slice(0, 10) >= data.period_start && t.createdAt.slice(0, 10) <= data.period_end).forEach(t => { categories[t.category] = (categories[t.category] || 0) + t.amount; }); return Object.entries(categories).sort((a, b) => b[1] - a[1]).map(([label, amount]) => ({ label, value: totalExpenses ? Math.round(amount / totalExpenses * 100) : 0 })); })()).map(({ label, value }) => <div className="expense-bar" key={label}><div><span>{label}</span><strong>{value}%</strong></div><span><i style={{ width: `${value}%` }}/></span></div>)}{!demo && !totalExpenses && <p className="empty-state">Your expense categories will appear as you record costs.</p>}</section><section className="next-step-card"><Sparkles size={26}/><span className="micro-label">A SIMPLE NEXT STEP</span><h2>Good habits.<br/>Better decisions.</h2><p>Keep a daily record of what comes in and what goes out. Your next insight starts there.</p><Link className="inline-link" href="/voice">Record today's activity <ArrowUpRight size={17}/></Link></section></div><div className="insights-disclaimer"><span>{demo ? "Sample analytics for product exploration. Switch to live records for your actual business data." : "Based only on your saved transactions. Net cash flow is not audited profit."}</span><button className="inline-link" onClick={() => setRevision(r => r + 1)} disabled={loading}><RefreshCw size={13}/>{loading ? "Refreshing…" : "Refresh records"}</button></div></div>;
}
