"use client";
import { useEffect, useRef, useState } from "react";
import { ShieldCheck, ShieldAlert, ArrowRight, AlertTriangle, Link2, KeyRound, Timer, LockKeyhole, Flag, Check, Smartphone, X } from "lucide-react";
import { PageHeading, Status } from "@/components/product/Primitives";
import { api, apiError, AgentResponse } from "@/lib/api";
import { useApp } from "@/context/AppContext";
const suspicious="জরুরি: আপনার বিকাশ অ্যাকাউন্ট বন্ধ হয়ে যাবে! এখনই https://bkash-verify.xyz এ ক্লিক করে আপনার OTP দিন।";
const safe="আপনার পেমেন্ট ৫০০ টাকা গ্রহণ করা হয়েছে। পিন কাউকে দেবেন না।";
export default function FraudPage(){
 const {freezeIncident,reportIncident,dismissIncident,fraudIncident}=useApp();
 const [message,setMessage]=useState(suspicious); const [result,setResult]=useState<AgentResponse|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const version=useRef(0);
 const analyze=async(text=message)=>{const current=++version.current;setBusy(true);setError("");setResult(null);try{const next=await api.fraudCheck(text);if(current===version.current)setResult(next);}catch(e){if(current===version.current)setError(apiError(e));}finally{if(current===version.current)setBusy(false);}};
 useEffect(()=>{analyze(suspicious);return()=>{version.current++;};},[]);
 const sample=(text:string)=>{setMessage(text);analyze(text);};
 const high=result?.risk_level==="High";const low=result?.risk_level==="Low";
 return <div className="product-page fraud-page"><PageHeading eyebrow="PAHARA · A LITTLE EXTRA PEACE OF MIND" title="Confidence before you click." description="A second pair of eyes for the messages that don't feel quite right." action={<Status><ShieldCheck size={13}/>Your fraud protection companion</Status>}/>
 <section className={`fraud-banner ${low?"safe":""}`}><div className="fraud-shield">{low?<ShieldCheck size={37}/>:<ShieldAlert size={37}/>}</div><div><span className="micro-label">MESSAGE SCREENING</span><h2>{busy?"Taking a closer look…":high?"Suspicious message detected":low?"No familiar red flags detected":result?"This message needs a closer look":"Let's check before you act."}</h2><p>{low?"Low risk is not proof of a genuine sender. Verify the payment in your own app.":"Pause before sharing information. A moment of caution can protect your business."}</p></div><div className="risk-badge"><span>RISK LEVEL</span><strong>{busy?"…":result?.risk_level?.toUpperCase()||"—"}</strong><span>{result?"AI-assisted screening":"Awaiting analysis"}</span></div></section>
 <div className="fraud-grid"><section className="panel message-panel"><div className="panel-heading"><div><span className="micro-label">THE MESSAGE IN QUESTION</span><h2>Let's take a closer look.</h2></div><Smartphone size={22}/></div><div className="segmented fraud-samples"><button className={message===suspicious?"selected":""} onClick={()=>sample(suspicious)}>Suspicious example</button><button className={message===safe?"selected":""} onClick={()=>sample(safe)}>Safe example</button></div><div className="message-envelope"><div className="message-sender"><span className="sms-avatar">SMS</span><div><strong>Incoming message</strong><span>Sender not independently verified</span></div><span>now</span></div><label htmlFor="fraud-message" className="sr-only">Message to check</label><textarea id="fraud-message" value={message} onChange={e=>{version.current++;setMessage(e.target.value);setResult(null);setBusy(false);}} rows={5} maxLength={8000}/><div className="message-footnote"><LockKeyhole size={12}/>Paste a message here. Never enter your actual PIN or OTP.</div></div><button className="button navy full-width" onClick={()=>analyze()} disabled={busy||!message.trim()}>{busy?"Checking the message…":"Check this message"}<ArrowRight size={17}/></button>{error&&<p role="alert" className="form-error">{error}</p>}</section>
 <section className="panel risk-explanation"><div className="panel-heading"><div><span className="micro-label">THE WHY BEHIND THE WARNING</span><h2>{result?"Here's what Pahara noticed.":"Your explanation will appear here."}</h2></div><span className="node-icon rose"><ShieldAlert size={20}/></span></div><div className="risk-reasons">{result?.reasons.map((reason,i)=>{const Icon=[KeyRound,Link2,Timer,AlertTriangle][i%4];return <div className="risk-reason" key={reason}><span className={low?"safe-icon":""}><Icon size={18}/></span><div><strong>{low?"No familiar warning signs":reason.includes("পিন")?"OTP or credential request":reason.includes("লিংক")?"Suspicious link":reason.includes("চাপ")?"Urgent request":"Needs your attention"}</strong><p>{reason}</p></div></div>;})}{busy&&<p className="muted">Reading the message and checking risk signals…</p>}</div><div className="pahara-advice"><ShieldCheck size={21}/><div><strong>Your next best step</strong><p>{low?"Open your payment app directly to confirm the transaction.":"Don't use the link or share an OTP. Open your payment app yourself and contact support through a trusted channel."}</p></div></div></section></div>
 <div className="fraud-action-strip"><div><span className="micro-label">YOU'RE IN CONTROL</span><h3>Keep your business one step ahead.</h3><p>Demo incident controls · these do not contact a bank or police.</p></div><div className="fraud-action-buttons"><button className="button soft" onClick={freezeIncident} disabled={fraudIncident.status==="frozen"}><LockKeyhole size={15}/>{fraudIncident.status==="frozen"?"Marked on hold":"Hold transaction"}</button><button className="button navy" onClick={reportIncident} disabled={fraudIncident.status==="reported"}><Flag size={15}/>{fraudIncident.status==="reported"?"Report marked":"Report incident"}</button><button className="icon-button" onClick={dismissIncident} aria-label="Dismiss incident"><X size={19}/></button></div></div>
 <div className="safety-principles">{[["Your PIN is only yours.","No genuine support agent needs your secret code."],["Verify in your own app.","An SMS alone does not confirm that money arrived."],["Pause when you're pressured.","Urgency is a reason to slow down, not speed up."]].map(([title,copy],i)=><div key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div>;
}
